name: build-application
on: [ push ]
jobs:
    build-application:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -   name: Build docker image
                run: docker build --tag gh-actions .

            -   name: Show images
                run: docker image ls

            -   name: Run docker image
                run: docker run gh-actions
